# Generated by Django 2.1.5 on 2019-02-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('water_g', models.FloatField(blank=True, null=True)),
                ('energy_kcal', models.FloatField(blank=True, null=True)),
                ('protein_g', models.FloatField(blank=True, null=True)),
                ('lipid_g', models.FloatField(blank=True, null=True)),
                ('ash_g', models.FloatField(blank=True, null=True)),
                ('carbohydrt_g', models.FloatField(blank=True, null=True)),
                ('fiber_g', models.FloatField(blank=True, null=True)),
                ('sugar_g', models.FloatField(blank=True, null=True)),
                ('calcium_mg', models.FloatField(blank=True, null=True)),
                ('iron_mg', models.FloatField(blank=True, null=True)),
                ('magnesium_mg', models.FloatField(blank=True, null=True)),
                ('phosphorus_mg', models.FloatField(blank=True, null=True)),
                ('potassium_mg', models.FloatField(blank=True, null=True)),
                ('sodium_mg', models.FloatField(blank=True, null=True)),
                ('zinc_mg', models.FloatField(blank=True, null=True)),
                ('copper_mg', models.FloatField(blank=True, null=True)),
                ('manganese_mg', models.FloatField(blank=True, null=True)),
                ('selenium_mg', models.FloatField(blank=True, null=True)),
                ('vit_c_mg', models.FloatField(blank=True, null=True)),
                ('thiamin_mg', models.FloatField(blank=True, null=True)),
                ('riboflavin_mg', models.FloatField(blank=True, null=True)),
                ('niacin_mg', models.FloatField(blank=True, null=True)),
                ('panto_acid_mg', models.FloatField(blank=True, null=True)),
                ('vit_B6_mg', models.FloatField(blank=True, null=True)),
                ('folate_mug', models.FloatField(blank=True, null=True)),
                ('folic_acid_mug', models.FloatField(blank=True, null=True)),
                ('food_folate_mug', models.FloatField(blank=True, null=True)),
                ('folate_dfe_mug', models.FloatField(blank=True, null=True)),
                ('choline_mg', models.FloatField(blank=True, null=True)),
                ('vit_B12_mug', models.FloatField(blank=True, null=True)),
                ('vit_A_iu', models.FloatField(blank=True, null=True)),
                ('vit_A_rae', models.FloatField(blank=True, null=True)),
                ('retinol_mug', models.FloatField(blank=True, null=True)),
                ('alpha_carot_mug', models.FloatField(blank=True, null=True)),
                ('beta_carot_mug', models.FloatField(blank=True, null=True)),
                ('beta_crypt_mug', models.FloatField(blank=True, null=True)),
                ('lycopene_mug', models.FloatField(blank=True, null=True)),
                ('lut_and_cea_mug', models.FloatField(blank=True, null=True)),
                ('vit_e_mug', models.FloatField(blank=True, null=True)),
                ('vit_d_mug', models.FloatField(blank=True, null=True)),
                ('vit_d_ui', models.FloatField(blank=True, null=True)),
                ('vit_k', models.FloatField(blank=True, null=True)),
                ('FA_sat_g', models.FloatField(blank=True, null=True)),
                ('FA_mono_g', models.FloatField(blank=True, null=True)),
                ('FA_poly_g', models.FloatField(blank=True, null=True)),
                ('cholestrl_mg', models.FloatField(blank=True, null=True)),
                ('gmwt_1', models.FloatField(blank=True, null=True)),
                ('gmwt_desc1', models.FloatField(blank=True, null=True)),
                ('gmwt_2', models.FloatField(blank=True, null=True)),
                ('gmwt_desc2', models.FloatField(blank=True, null=True)),
                ('refuse_pct', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
