# Generated by Django 2.1.5 on 2019-02-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodrition_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='energy_kcal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
