# Generated by Django 2.1.5 on 2019-02-19 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodrition_api', '0003_foodimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='ndb_no',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
